# Minutes of meeting {#minutesOfMeeting}
In this section short minutes of meetings are kept so that people who join later can easily get up to speed


## 21-03-2018

Discussing concept, elias volunteered to create block diagram
Trying to get Xbox 360 controller to work with raspi and mac, failed since controller was not accessable from python eventhough it was accessable on the mac via system preference pane.

## 15-02-2018

### Plattformen

#### Sunfounder

link für amazon bestellung

https://www.amazon.de/SunFounder-Roboterbausatz-Programmierbarer-Auto-Roboter-Compatible/dp/B01ANIY3EC/ref=sr_1_1?ie=UTF8&qid=1518719324&sr=8-1&keywords=sunfounder 



#### Basis Donkey car

http://www.donkeycar.com/
http://docs.donkeycar.com/
http://docs.donkeycar.com/guide/build_hardware/
https://makezine.com/projects/build-autonomous-rc-car-raspberry-pi/
https://diyrobocars.com/
* Kinect / Wii 

https://sungjik.wordpress.com/2015/09/28/my_personal_robotic_companion/



* Basis Carputer https://github.com/otaviogood/carputer

#### Openzeka

https://www.youtube.com/results?search_query=openzeka

### neuronales Netz

#### Hardware

* Nvida Jetson TX2 

* paralella



#### kontakt

* Slack channel: donkeycar.slack.com

* meetup




## 08-02-2018

### Location: Shackspace

What was meant to be a an introduction into the shackspace evolved to a discussion about various topics

### Studie Hackerspaces
+ http://www.cowerk.org/home/single/article/befragungsergebnisse-wertschoepfung-in-offenen-werkstaetten.html
+ https://www.heise.de/make/meldung/Studie-Neue-Produktionsmodelle-in-offenen-Werkstaetten-3504625.html
 + https://www.heise.de/make/meldung/Kein-Freifahrtschein-fuer-Hackerspaces-Benutzung-auf-eigene-Gefahr-3955181.html 
 
### Buchtipps
* Makers: Das Internet der Dinge: die nächste industrielle Revolution, Chris Anderson
* Zero 
* Thinking fast and slow, Kahnemann
* Gunter Dueck
   * https://www.omnisophie.com  
   * Vorträge auf der Re-publica als Einstieg
https://www.youtube.com/results?search_query=gunter+dueck
* Biohacking: Gentechnologie für alle, Rüdiger Trojok
* Biohacking: Gentechnik aus der Garage, Hanno Charisius

### RoboCar

Elias says he would like to be build an autonomous model car, probably based on Raspberry Pi. In order to end dreaming and start doing we fixed the next meeting to 15th of February where we want to start defining concepts.



